/* ----------------- Bancos ------------------- */
 const banks = {

  BANCO_DE_BOGOTÁ: 1,
  BANCO_POPULAR: 2,
  BANCO_CORPBANCA: 3,
  BANCOLOMBIA: 4,
  CITIBANK: 5,
  BANCO_GNB_SUDAMERIS: 6,
  BBVA_COLOMBIA: 7,
  ITAÚ: 8,
  BANCO_COLPATRIA: 9,
  BANCO_DE_OCCIDENTE: 10,
  BANCO_CAJA_SOCIAL: 11,
  BANCO_AGRARIO: 12,
  BNP_PARIBAS: 13,
  BANCO_DAVIVIENDA: 14,
  BANCO_AV_VILLAS: 15,
  BANCO_PROCREDIT: 16,
  BANCO_PICHINCHA: 17,
  BANCOOMEVA: 18,
  BANCO_FALABELLA: 19,
  BANCO_FINANDINA: 20,
  BANCO_MULTIBANK: 21,
  BANCO_SANTANDER_DE_NEGOCIOS_COLOMBIA: 22,
  COOPCENTRAL: 23,
  BANCO_COMPARTIR: 24,
  CORFICOLOMBIANA: 25,
  FINANCIERA_JURIDISCOOP: 26,
  COOPERATIVA_FINANCIERA_DE_ANTIOQUIA: 27,
  COTRAFA_COOPERATIVA_FINANCIERA: 28,
  CONFIAR: 29,
  COLTEFINANCIERA: 30,
  DAVIPLATA: 31,
  NEQUI: 32,
  EFECTY: 33,
  AVANZOAPP: 34,
};

module.exports = {
  banks
}