-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 21:05:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AvanzoDB` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `maximumAmount` INT NOT NULL,
  `partialCapacity` INT NOT NULL DEFAULT 0,
  `documentsUploaded` TINYINT NOT NULL,
  `montlyFee` INT NOT NULL,
  `totalInterest` INT NOT NULL,
  `totalFeeAdministration` INT NOT NULL,
  `lastAdministrationDate` DATETIME NOT NULL,
  `totalOtherCollection` INT NOT NULL DEFAULT 0,
  `totalRemainder` INT NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `fk_Account_Client1_idx` (`Client_idClient` ASC)  ,
  CONSTRAINT `fk_Account_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrator` (
  `idAdministrator` INT NOT NULL AUTO_INCREMENT,
  `adminType` VARCHAR(45) NOT NULL,
  `nickName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Audit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Audit` (
  `idAudit` INT NOT NULL,
  `params` VARCHAR(45) NOT NULL,
  `page` VARCHAR(45) NOT NULL,
  `requestDate` DATETIME NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idAudit`),
  INDEX `fk_Audit_User1_idx` (`User_idUser` ASC)  ,
  CONSTRAINT `fk_Audit_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Auth` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Auth` (
  `idAuth` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idAuth`),
  INDEX `fk_Auth_User1_idx` (`User_idUser` ASC)  ,
  CONSTRAINT `fk_Auth_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bank` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bank` (
  `idOutLays` INT NOT NULL AUTO_INCREMENT,
  `outlayAccount` VARCHAR(45) NOT NULL,
  `outlayType` VARCHAR(45) NOT NULL,
  `accountType` VARCHAR(45) NULL,
  PRIMARY KEY (`idOutLays`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `identificationId` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `documentType` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NOT NULL,
  `fixedNumber` INT NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `expeditionDate` DATETIME NOT NULL,
  `contractType` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `entryDate` DATETIME NOT NULL,
  `profession` VARCHAR(45) NOT NULL,
  `genus` VARCHAR(45) NULL,
  `accountBank` VARCHAR(45) NOT NULL,
  `accountType` VARCHAR(45) NOT NULL,
  `accountNumber` INT NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `Company_idCompany` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_Company1_idx` (`Company_idCompany` ASC)  ,
  CONSTRAINT `fk_Client_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `nit` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `maximumSplit` INT NOT NULL,
  `defaultAmount` INT NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `socialReason` VARCHAR(45) NOT NULL,
  `economyActivity` VARCHAR(45) NOT NULL,
  `CompanySalaries_idCompanySalaries` INT NOT NULL,
  PRIMARY KEY (`idCompany`),
  INDEX `fk_Company_CompanySalaries1_idx` (`CompanySalaries_idCompanySalaries` ASC)  ,
  CONSTRAINT `fk_Company_CompanySalaries1`
    FOREIGN KEY (`CompanySalaries_idCompanySalaries`)
    REFERENCES `mydb`.`CompanySalaries` (`idCompanySalaries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompanyMembers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CompanyMembers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CompanyMembers` (
  `idCompanyMembers` INT NOT NULL,
  `memberName` VARCHAR(45) NOT NULL,
  `memberId` INT NOT NULL,
  `profession` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NOT NULL,
  `memberEmail` VARCHAR(45) NOT NULL,
  `isLegalRepresentant` TINYINT NOT NULL,
  `Company_idCompany` INT NOT NULL,
  PRIMARY KEY (`idCompanyMembers`),
  INDEX `fk_CompanyMembers_Company1_idx` (`Company_idCompany` ASC)  ,
  CONSTRAINT `fk_CompanyMembers_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompanySalaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CompanySalaries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CompanySalaries` (
  `idCompanySalaries` INT NOT NULL,
  `companyRate` VARCHAR(45) NOT NULL,
  `companyFirstDate` VARCHAR(45) NOT NULL,
  `companySecondDate` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompanySalaries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DocumentTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DocumentTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DocumentTypes` (
  `idDocumentTypes` INT NOT NULL,
  `typeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocumentTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Documents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Documents` (
  `idDocuments` INT NOT NULL AUTO_INCREMENT,
  `documentType` VARCHAR(45) NOT NULL,
  `file` BINARY(25) NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `registeredBy` DATETIME NOT NULL,
  `Company_idCompany` INT NOT NULL,
  PRIMARY KEY (`idDocuments`),
  INDEX `fk_Documents_Company1_idx` (`Company_idCompany` ASC)  ,
  CONSTRAINT `fk_Documents_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InterestRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InterestRequest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InterestRequest` (
  `idInterestRequest` INT NOT NULL AUTO_INCREMENT,
  `interestValue` DECIMAL(10) NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  PRIMARY KEY (`idInterestRequest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ManagementPayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ManagementPayment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ManagementPayment` (
  `managemntPaymentId` INT NOT NULL AUTO_INCREMENT,
  `managementPaymentValue` INT NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  PRIMARY KEY (`managemntPaymentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Observations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Observations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Observations` (
  `idObservations` INT NOT NULL AUTO_INCREMENT,
  `observationContent` VARCHAR(250) NOT NULL,
  `observationType` VARCHAR(45) NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `createdDate` DATETIME NOT NULL,
  PRIMARY KEY (`idObservations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `Transaction_idTransaction` INT NOT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `fk_Payment_Transaction1_idx` (`Transaction_idTransaction` ASC)  ,
  CONSTRAINT `fk_Payment_Transaction1`
    FOREIGN KEY (`Transaction_idTransaction`)
    REFERENCES `mydb`.`Transaction` (`idTransaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PreRequestDates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PreRequestDates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PreRequestDates` (
  `idPreRequestDates` INT NOT NULL,
  `firstDate` DATETIME NOT NULL,
  `firstQuantity` VARCHAR(45) NOT NULL,
  `secondDate` DATETIME NULL,
  `secondQuantity` VARCHAR(45) NULL,
  `thirdDate` DATETIME NULL,
  `thirdQuantity` VARCHAR(45) NULL,
  PRIMARY KEY (`idPreRequestDates`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `idRequest` INT NOT NULL AUTO_INCREMENT,
  `creditNumber` INT NOT NULL,
  `quantity` INT NOT NULL,
  `numberPayments` INT NOT NULL,
  `outlayAccount` VARCHAR(45) NOT NULL,
  `outlayType` VARCHAR(45) NOT NULL,
  `approveHumanResources` VARCHAR(45) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `RequestState_idRequestState` INT NOT NULL,
  `Observations_idObservations` INT NOT NULL,
  `RequestFiles_idRequestFiles` INT NOT NULL,
  `Transaction_idTransaction` INT NOT NULL,
  `PreRequestDates_idPreRequestDates` INT NOT NULL,
  `Account_idAccount` INT NULL,
  PRIMARY KEY (`idRequest`),
  INDEX `fk_Request_RequestState1_idx` (`RequestState_idRequestState` ASC)  ,
  INDEX `fk_Request_Observations1_idx` (`Observations_idObservations` ASC)  ,
  INDEX `fk_Request_RequestFiles1_idx` (`RequestFiles_idRequestFiles` ASC)  ,
  INDEX `fk_Request_Account1_idx` (`Account_idAccount` ASC)  ,
  INDEX `fk_Request_Transaction1_idx` (`Transaction_idTransaction` ASC)  ,
  INDEX `fk_Request_PreRequestDates1_idx` (`PreRequestDates_idPreRequestDates` ASC)  ,
  CONSTRAINT `fk_Request_RequestState1`
    FOREIGN KEY (`RequestState_idRequestState`)
    REFERENCES `mydb`.`RequestState` (`idRequestState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Observations1`
    FOREIGN KEY (`Observations_idObservations`)
    REFERENCES `mydb`.`Observations` (`idObservations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_RequestFiles1`
    FOREIGN KEY (`RequestFiles_idRequestFiles`)
    REFERENCES `mydb`.`RequestFiles` (`idRequestFiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Account1`
    FOREIGN KEY (`Account_idAccount`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Transaction1`
    FOREIGN KEY (`Transaction_idTransaction`)
    REFERENCES `mydb`.`Transaction` (`idTransaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_PreRequestDates1`
    FOREIGN KEY (`PreRequestDates_idPreRequestDates`)
    REFERENCES `mydb`.`PreRequestDates` (`idPreRequestDates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequestFiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RequestFiles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RequestFiles` (
  `idRequestFiles` INT NOT NULL,
  `fileType` VARCHAR(45) NOT NULL,
  `file` BINARY NOT NULL,
  PRIMARY KEY (`idRequestFiles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequestOutLay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RequestOutLay` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RequestOutLay` (
  `idRequestOutLay` INT NOT NULL,
  `outLayDate` VARCHAR(45) NOT NULL,
  `totalInterest` INT NOT NULL,
  `lastComputedDate` VARCHAR(45) NOT NULL,
  `wasComputed` VARCHAR(45) NOT NULL,
  `Request_idRequest` INT NOT NULL,
  PRIMARY KEY (`idRequestOutLay`),
  INDEX `fk_RequestOutLay_Request1_idx` (`Request_idRequest` ASC)  ,
  CONSTRAINT `fk_RequestOutLay_Request1`
    FOREIGN KEY (`Request_idRequest`)
    REFERENCES `mydb`.`Request` (`idRequest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequestState`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RequestState` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RequestState` (
  `idRequestState` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  PRIMARY KEY (`idRequestState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `priority` INT NOT NULL,
  `roleName` VARCHAR(45) NOT NULL,
  `createdDate` VARCHAR(45) NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `transactionType` VARCHAR(45) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `Account_idAccount` INT NOT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `fk_Transaction_Account1_idx` (`Account_idAccount` ASC)  ,
  CONSTRAINT `fk_Transaction_Account1`
    FOREIGN KEY (`Account_idAccount`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `registeredBy` INT NOT NULL,
  `registeredDate` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  `Role_idRole` INT NOT NULL,
  `Client_idClient` INT NULL,
  `Company_idCompany` INT NULL,
  `Administrator_idAdministrator` INT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Client1_idx` (`Client_idClient` ASC)  ,
  INDEX `fk_User_Company1_idx` (`Company_idCompany` ASC)  ,
  INDEX `fk_User_Administrator1_idx` (`Administrator_idAdministrator` ASC)  ,
  INDEX `fk_User_Role1_idx` (`Role_idRole` ASC)  ,
  CONSTRAINT `fk_User_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Administrator1`
    FOREIGN KEY (`Administrator_idAdministrator`)
    REFERENCES `mydb`.`Administrator` (`idAdministrator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
